colorScheme = "slate"
defaultAppearance = "dark"  # valid options: light or dark
autoSwitchAppearance = true

# defaultThemeColor = "#FFFFFF"

# enableSearch = true
enableCodeCopy = true

# robots = ""
fingerprintAlgorithm = "sha256"

[header]
layout = "basic"

[footer]
showCopyright = true
showThemeAttribution = false
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "profile"
showRecent = true
recentLimit = 6
