name: Deploy Hugo site to Pages

on:
  push:
    branches: [main]
  schedule:
    # Daily at 11:00 UTC (7am EDT / 6am EST for America/Toronto)
    - cron: "0 11 * * *"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true

      # Cache Hugo & Go module artifacts
      - name: Cache Hugo/Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/hugo
            ~/.cache/go-build
            ~/go/pkg/mod
            ./resources
          key: ${{ runner.os }}-hugo-${{ hashFiles('**/go.mod', '**/go.sum', 'hugo.toml', 'hugo.yaml', 'hugo.json') }}
          restore-keys: |
            ${{ runner.os }}-hugo-
            ${{ runner.os }}-
          
      - name: Build site
        env:
          HUGO_ENV: production
          HUGO_ENVIRONMENT: production
        run: hugo --minify --baseURL "https://www.orchestratorsnotebook.com/"
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
