name: Deploy Hugo site to Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true

      - name: Get Hugo modules
        run: |
          hugo mod get -u ./...
          hugo mod tidy
          hugo mod vendor
      - name: Build site
        run: hugo --minify --baseURL "https://www.orchestratorsnotebook.com/"
      - name: Add CNAME and .nojekyll
        run: |
          echo "www.orchestratorsnotebook.com" > public/CNAME
          touch public/.nojekyll
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
